
name: 'Build Mriya'
on:
  - push
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["mriya_left","mriya_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'

